apiVersion: apps/v1
kind: Deployment
metadata:
  name: p20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p20
  template:
    metadata:
      labels:
        app: p20
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p20
        ports:
        - containerPort: 80
